/**
 * Fork-owned: the task tools' descriptions and prompt guidelines, verbatim from pi-tasks `src/index.ts` at
 * 83480bd, which follows Claude Code's tools. TaskOutput and TaskStop describe agents only: their shell
 * branches are dropped (D49).
 */

export const TASK_CREATE_DESCRIPTION =
	'Use this tool to create a structured task list for your current coding session. This helps you track progress, organize complex tasks, and demonstrate thoroughness to the user.\nIt also helps the user understand the progress of the task and overall progress of their requests.\n\n## When to Use This Tool\n\nUse this tool proactively in these scenarios:\n\n- Complex multi-step tasks - When a task requires 3 or more distinct steps or actions\n- Non-trivial and complex tasks - Tasks that require careful planning or multiple operations\n- Plan mode - When using plan mode, create a task list to track the work\n- User explicitly requests todo list - When the user directly asks you to use the todo list\n- User provides multiple tasks - When users provide a list of things to be done (numbered or comma-separated). Create them all in one response with one TaskCreate call per task\n- After receiving new instructions - Immediately capture user requirements as tasks\n- When you start working on a task - Mark it as in_progress BEFORE beginning work\n- After completing a task - Mark it as completed and add any new follow-up tasks discovered during implementation\n\n## When NOT to Use This Tool\n\nSkip using this tool when:\n- There is only a single, straightforward task\n- The task is trivial and tracking it provides no organizational benefit\n- The task can be completed in less than 3 trivial steps\n- The task is purely conversational or informational\n\nNOTE that you should not use this tool if there is only one trivial task to do. In this case you are better off just doing the task directly.\n\n## Task Fields\n\n- **subject**: A brief, actionable title in imperative form (e.g., "Fix authentication bug in login flow")\n- **description**: Detailed description of what needs to be done, including context and acceptance criteria\n- **activeForm** (optional): Present continuous form shown in the spinner when the task is in_progress (e.g., "Fixing authentication bug"). If omitted, the spinner shows the subject instead.\n\nAll tasks are created with status `pending`.\n\n## Tips\n\n- Create tasks with clear, specific subjects that describe the outcome\n- Include enough detail in the description for another agent to understand and complete the task\n- After creating tasks, use TaskUpdate to set up dependencies (blocks/blockedBy) if needed\n- Check TaskList first to avoid creating duplicate tasks\n- Include `agentType` (e.g., "general-purpose", "Explore") to mark tasks for subagent execution via TaskExecute\n- To create several tasks at once, call TaskCreate multiple times in a single response — independent tool calls run in parallel, so the whole batch is created in one turn (one task per call).';

export const TASK_LIST_DESCRIPTION =
	"Use this tool to list all tasks in the task list.\n\n## When to Use This Tool\n\n- To see what tasks are available to work on (status: 'pending', no owner, not blocked)\n- To check overall progress on the project\n- To find tasks that are blocked and need dependencies resolved\n- After completing a task, to check for newly unblocked work or claim the next available task\n- **Prefer working on tasks in ID order** (lowest ID first) when multiple tasks are available, as earlier tasks often set up context for later ones\n\n## Output\n\nReturns a summary of each task:\n- **id**: Task identifier (use with TaskGet, TaskUpdate)\n- **subject**: Brief description of the task\n- **status**: 'pending', 'in_progress', or 'completed'\n- **owner**: Agent ID if assigned, empty if available\n- **blockedBy**: List of open task IDs that must be resolved first (tasks with blockedBy cannot be claimed until dependencies resolve)\n\nUse TaskGet with a specific task ID to view full details including description and comments.";

export const TASK_GET_DESCRIPTION =
	"Use this tool to retrieve a task by its ID from the task list.\n\n## When to Use This Tool\n\n- When you need the full description and context before starting work on a task\n- To understand task dependencies (what it blocks, what blocks it)\n- After being assigned a task, to get complete requirements\n\n## Output\n\nReturns full task details:\n- **subject**: Task title\n- **description**: Detailed requirements and context\n- **status**: 'pending', 'in_progress', or 'completed'\n- **blocks**: Tasks waiting on this one to complete\n- **blockedBy**: Tasks that must complete before this one can start\n\n## Tips\n\n- After fetching a task, verify its blockedBy list is empty before beginning work.\n- Use TaskList to see all tasks in summary form.";

export const TASK_UPDATE_DESCRIPTION =
	'Use this tool to update a task in the task list.\n\n## When to Use This Tool\n\n**Before starting work on a task:**\n- Mark it in_progress BEFORE beginning — do not start work without updating status first\n- After resolving, call TaskList to find your next task\n\n**Mark tasks as resolved:**\n- When you have completed the work described in a task\n- When a task is no longer needed or has been superseded\n- IMPORTANT: Always mark your assigned tasks as resolved when you finish them\n- After resolving, call TaskList to find your next task\n\n- ONLY mark a task as completed when you have FULLY accomplished it\n- If you encounter errors, blockers, or cannot finish, keep the task as in_progress\n- When blocked, create a new task describing what needs to be resolved\n- Never mark a task as completed if:\n  - Tests are failing\n  - Implementation is partial\n  - You encountered unresolved errors\n  - You couldn\'t find necessary files or dependencies\n\n**Delete tasks:**\n- When a task is no longer relevant or was created in error\n- Setting status to `deleted` permanently removes the task\n\n**Update task details:**\n- When requirements change or become clearer\n- When establishing dependencies between tasks\n\n## Fields You Can Update\n\n- **status**: The task status (see Status Workflow below)\n- **subject**: Change the task title (imperative form, e.g., "Run tests")\n- **description**: Change the task description\n- **activeForm**: Present continuous form shown in spinner when in_progress (e.g., "Running tests")\n- **owner**: Change the task owner (agent name)\n- **metadata**: Merge metadata keys into the task (set a key to null to delete it)\n- **addBlocks**: Mark tasks that cannot start until this one completes\n- **addBlockedBy**: Mark tasks that must complete before this one can start\n\n## Status Workflow\n\nStatus progresses: `pending` → `in_progress` → `completed`\n\nUse `deleted` to permanently remove a task.\n\n## Staleness\n\nMake sure to read a task\'s latest state using `TaskGet` before updating it.\n\n## Examples\n\nMark task as in progress when starting work:\n```json\n{"taskId": "1", "status": "in_progress"}\n```\n\nMark task as completed after finishing work:\n```json\n{"taskId": "1", "status": "completed"}\n```\n\nDelete a task:\n```json\n{"taskId": "1", "status": "deleted"}\n```\n\nClaim a task by setting owner:\n```json\n{"taskId": "1", "owner": "my-name"}\n```\n\nSet up task dependencies:\n```json\n{"taskId": "2", "addBlockedBy": ["1"]}\n```';

export const TASK_OUTPUT_DESCRIPTION =
	"- Retrieves the output of the subagent that runs a task, running or completed\n- Takes a task_id parameter: a task ID, or the ID of the agent that runs it\n- Returns the task's status with the agent's result or error\n- Use block=true (default) to wait for the agent to finish\n- Use block=false for a non-blocking check of the current status\n- Task IDs can be found using TaskList or the /tasks command";

export const TASK_STOP_DESCRIPTION =
	"- Stops the subagent that runs a task\n- Takes a task_id parameter: a task ID, or the ID of the agent that runs it\n- Marks the task completed and keeps the agent's partial output\n- Use this tool when you need to terminate a long-running task";

export const TASK_EXECUTE_DESCRIPTION =
	'Execute one or more tasks as subagents.\n\n## When to Use This Tool\n\n- To start execution of tasks that have `agentType` set (created via TaskCreate with agentType parameter)\n- Tasks must be `pending` with all blockedBy dependencies `completed`\n- Each task runs as an independent background subagent\n\n## Parameters\n\n- **task_ids**: Array of task IDs to execute\n- **additional_context**: Extra context appended to each agent\'s prompt\n- **model**: Model override for agents (e.g., "sonnet", "haiku")\n- **thinking**: Thinking level override for agents (e.g., "low", "high")\n- **max_turns**: Maximum turns per agent';

export const TASK_CREATE_GUIDELINES: readonly string[] = [
	"When working on complex multi-step tasks, use TaskCreate to track progress and TaskUpdate to update status.",
	"Mark tasks as in_progress before starting work and completed when done.",
	"Use TaskList to check for available work after completing a task.",
];

export const TASK_EXECUTE_GUIDELINES: readonly string[] = [
	"Never use the Agent tool for tasks launched via TaskExecute — agents are already running.",
];
